---
default_stages: [commit, push]
default_language_version:
  # force all unspecified Python hooks to run python3
  python: python3
minimum_pre_commit_version: "1.20.0"
repos:
  - repo: meta
    hooks:
      - id: identity
      - id: check-hooks-apply
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
        exclude: ^docs/assets/xsl/rss\.xsl$|^docs/feed\.xslt\.xml$|^docs/opensearch\.xml$|^docs/rss\.xml$|^logorama/feed\.xml$
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: ^charts/assets/.*$|^charts/lang/README\.de\.md$|^charts/log\.txt$|^charts/README\.md$|^docs/assets/js/.*$|^docs/assets/games/.*$|rubycritic/.*$
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--no-sort-keys"
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        exclude: ^rubycritic/.*$
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: Run black on Python files
  # - repo: https://github.com/asottile/dead
  #  rev: v1.4.0
  #  hooks:
  #    - id: dead
  #      name: Dead simple python dead code detection
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.0.1
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.6
    hooks:
      - id: markdownlint # Configure in .mdlrc
      - id: reek
      - id: rubocop
      - id: shellcheck
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.13
    hooks:
      - id: forbid-tabs
        exclude: ^doc/Makefile$|go\.mod$|go\.sum$|.*\.go$
      - id: remove-tabs
        exclude: ^doc/Makefile$|go\.mod$|go\.sum$|.*\.go$
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint
        name: Run markdownlint
        entry: markdownlint -c .github/linters/.markdown-lint.yml .
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        name: Check YAML files with yamllint
        entry: yamllint --strict -c .github/linters/.yaml-lint.yml .
        types: [yaml]
  # - repo: https://github.com/PyCQA/bandit
  #  rev: 1.7.0
  #  hooks:
  #    - id: bandit
  # - repo: https://gitlab.com/pycqa/flake8
  #  rev: 3.8.4
  #  hooks:
  #    - id: flake8
  # - repo: https://github.com/syntaqx/git-hooks
  #  rev: v0.0.16
  #  hooks:
  #    - id: go-fmt
  #    - id: go-test
  #    - id: go-mod-tidy
