name: Lint

on: [pull_request]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  build:
    permissions:
      contents: read  # for actions/checkout to fetch code
      statuses: write  # for github/super-linter to mark status of each linter run
    name: GitHub Super-Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - uses: github/super-linter@v4.9.7
        env:
          DEFAULT_BRANCH: main
          ERROR_ON_MISSING_EXEC_BIT: true
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          # VALIDATE_EDITORCONFIG: true
          VALIDATE_GO: true
          VALIDATE_MARKDOWN: true
          VALIDATE_PHP: true
          VALIDATE_PYTHON_FLAKE8: true
          VALIDATE_RUBY: true
          VALIDATE_YAML: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
